# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # @typescript-eslnt publishes new updates every Monday:
      # https://typescript-eslint.io/maintenance/releases#latest
      # Since we use multiple packages that need to be kept in sync with each other,
      # check for updates on Tuesday instead to avoid mismatched versions.
      # Remove after https://github.com/dependabot/dependabot-core/issues/1296 is implemented.
      day: "tuesday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Parity with npm.
      day: "tuesday"
