name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint
        env:
          NODE_ENV: production

      - name: npm run build
        run: npm run build
