name: CI
on:
- push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build
