name: Deploy to GitHub Pages
on:
  workflow_run:
    workflows:
      - CI
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
